'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CompRelForm

    '''<summary>
    '''lWO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lWO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lCompPn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCompPn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lUnitNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lUnitNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lCompReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCompReg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lUnitModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lUnitModel As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lDateHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lDateHead As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lCompDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lCompDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkVisInsp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVisInsp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVisInsp3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVisInsp4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVisInsp5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVisInsp6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAsmChk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAsmChk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTstPerform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTstPerform As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPhotoComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPhotoComp As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAntiRust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAntiRust As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPaintQuality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPaintQuality As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWrapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWrapping As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEnSealIns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnSealIns As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkInstChk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInstChk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tRemarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkStatAcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStatAcc As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkStatRjt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStatRjt As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InspBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''InspDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspDate As Global.System.Web.UI.WebControls.Label
End Class
