'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FiveSDetails

    '''<summary>
    '''MenuTCRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuTCRC As Global.TCRCWebV2.MenuTCRC1

    '''<summary>
    '''FiveSDetailsForm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FiveSDetailsForm As Global.TCRCWebV2.FiveSDetailsForm

    '''<summary>
    '''bBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bBack As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents head1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddLeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddLeader As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''bassign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bassign As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bSupvApv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bSupvApv As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rptArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptArea As Global.System.Web.UI.WebControls.Repeater
End Class
