'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ComponentRelEdit

    '''<summary>
    '''tWONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tWONo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tCompPN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tCompPN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tUnitNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tUnitNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tCompReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tCompReg As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tUnitModel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tUnitModel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tCompDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tCompDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkVisInsp1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVisInsp2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVisInsp3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVisInsp4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVisInsp5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp5 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkVisInsp6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVisInsp6 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAsmChk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAsmChk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkTstPerform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkTstPerform As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPhotoComp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPhotoComp As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkAntiRust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAntiRust As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkPaintQuality control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPaintQuality As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkWrapping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkWrapping As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkEnSealIns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkEnSealIns As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkInstChk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkInstChk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''tRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tRemarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkStatAcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStatAcc As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''chkStatRjt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkStatRjt As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''InspBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspBy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''InspDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents InspDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''bSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Button1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Button1 As Global.System.Web.UI.WebControls.Button
End Class
