'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class indexWS

    '''<summary>
    '''MenuTCRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuTCRC As Global.TCRCWebV2.MenuTCRC1

    '''<summary>
    '''hFullName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hFullName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hTitle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hTitle As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hEmail As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hSupv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hSupv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''hJobCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hJobCost As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bMeaWorksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bMeaWorksheet As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bMeaTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bMeaTemplate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bPrelimWorksheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bPrelimWorksheet As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bPrelimTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bPrelimTemplate As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bassm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bassm As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bCompRelease control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bCompRelease As Global.System.Web.UI.WebControls.LinkButton
End Class
