'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class MeaInspWorksheetRev

    '''<summary>
    '''MenuTCRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuTCRC As Global.TCRCWebV2.MenuTCRC1

    '''<summary>
    '''lwo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lwo As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lhWO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lhWO As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lWODesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lWODesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rpt_section control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpt_section As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''MainDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''MeaInspRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MeaInspRemark As Global.TCRCWebV2.MeaInspRemark

    '''<summary>
    '''lSectionName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSectionName As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lSubSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSubSection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bEditRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bEditRemark As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''imgSection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSection As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''lSectionRemark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSectionRemark As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptHeader As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''rptItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptItem As Global.System.Web.UI.WebControls.Repeater
End Class
