'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AssemblyMea1

    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''eid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents eid As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''evaltype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents evaltype As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''lActitivty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lActitivty As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lMeaType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lMeaType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lSpec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSpec As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lvalue control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvalue As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''mea1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mea1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mea2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mea2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''emeanum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emeanum As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lunit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lunit As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''mea3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mea3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''emeatext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents emeatext As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''bsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsave As Global.System.Web.UI.WebControls.LinkButton
End Class
