'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AssemblyMea

    '''<summary>
    '''MenuTCRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuTCRC As Global.TCRCWebV2.MenuTCRC1

    '''<summary>
    '''ScrollPosition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScrollPosition As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''AssemblyMea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssemblyMea As Global.TCRCWebV2.AssemblyMea1

    '''<summary>
    '''AssemblyGallery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssemblyGallery As Global.TCRCWebV2.AssemblyGallery

    '''<summary>
    '''lwono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lwono As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lwodesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lwodesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''AssemblyMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssemblyMenu As Global.TCRCWebV2.AssemblyMenu

    '''<summary>
    '''bgallery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bgallery As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bswp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bswp As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bprint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bprint As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bBack As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lSectionProg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSectionProg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pSectionProg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pSectionProg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lSectionLH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSectionLH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pSectionLH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pSectionLH As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddsection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddsection As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lsection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''imgGp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgGp As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''rpt_mea2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpt_mea2 As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''gv_supv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_supv As Global.System.Web.UI.WebControls.GridView
End Class
