'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AssemblyChk

    '''<summary>
    '''MenuTCRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuTCRC As Global.TCRCWebV2.MenuTCRC1

    '''<summary>
    '''lwono control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lwono As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lwodesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lwodesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''AssemblyMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssemblyMenu As Global.TCRCWebV2.AssemblyMenu

    '''<summary>
    '''lSectionProg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lSectionProg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''pSectionProg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pSectionProg As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ddsection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddsection As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lsection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lsection As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''bchk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bchk As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bna control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bna As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''gv_chk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_chk As Global.System.Web.UI.WebControls.GridView
End Class
