'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PrelimTemplateDetails

    '''<summary>
    '''MenuTCRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuTCRC As Global.TCRCWebV2.MenuTCRC1

    '''<summary>
    '''bexport control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bexport As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bclose control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bclose As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''rpt_pict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpt_pict As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''ddsection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddsection As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tPN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tPN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tpartdesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpartdesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddndt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddndt As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddcondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddcondition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dddeactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dddeactive As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''bsearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsearch As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''sidgp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sidgp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sunitdesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sunitdesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ssheetname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ssheetname As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sglobalpn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sglobalpn As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''smainid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents smainid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sdeactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sdeactive As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''screateby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents screateby As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''screatedate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents screatedate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''smodby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents smodby As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''smoddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents smoddate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rptPrelim control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rptPrelim As Global.System.Web.UI.WebControls.Repeater
End Class
