'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PrelimTemplateDetailsEdit

    '''<summary>
    '''MenuTCRC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MenuTCRC As Global.TCRCWebV2.MenuTCRC1

    '''<summary>
    '''hidpartlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hidpartlist As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''sid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spn As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''spndesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spndesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''tpartremark control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tpartremark As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tspec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tspec As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddsection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddsection As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''tseq control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tseq As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tnopict control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tnopict As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tqty control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tqty As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddndt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddndt As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddnormalcondition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddnormalcondition As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''dddeactive control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dddeactive As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''bsave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bsave As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''bback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents bback As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''sidgp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sidgp As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sunitdesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sunitdesc As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ssheetname control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ssheetname As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sglobalpn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sglobalpn As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sregdate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sregdate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''sregby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sregby As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''smoddate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents smoddate As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''smodby control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents smodby As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
